pipeline {
  agent any

  options {
    disableConcurrentBuilds()
    timeout(time: 20, unit: 'MINUTES')
    timestamps()
  }

  environment {
    DEPLOY_PATH = '/home/dbadev01/dba-dev-testing/deploy-dba_alld_project/deploy/dev'
    DOCKER_BUILDKIT = '1'
  }

  stages {

    stage('Clean Workspace') {
      steps {
        deleteDir()
      }
    }

    stage('Checkout Source') {
      steps {
        git branch: 'main',
            url: 'git@github.com:thinkvalleyacademy/DBA-SOFTWARE.git'
      }
    }

    stage('Generate Image Tag') {
      steps {
        script {
          env.IMAGE_TAG = sh(
            script: "git rev-parse --short HEAD",
            returnStdout: true
          ).trim()
        }
        echo "Building tag: ${env.IMAGE_TAG}"
      }
    }

    stage('Build Backend Image') {
      steps {
        dir('backend-src') {
          sh """
            docker build -t dba-backend:${env.IMAGE_TAG} .
          """
        }
      }
    }

    stage('Build Frontend Image') {
      steps {
        dir('frontend-src') {
          sh """
            docker build -t dba-frontend:${env.IMAGE_TAG} .
          """
        }
      }
    }

    stage('Deploy DEV') {
      steps {
        sh """
          cd ${DEPLOY_PATH}
          TAG=${env.IMAGE_TAG} docker compose --env-file .env down --remove-orphans
          TAG=${env.IMAGE_TAG} docker compose --env-file .env up -d
        """
      }
    }

    stage('Health Check') {
      steps {
        sleep 25
        sh "curl -f http://localhost:5082/dba-alld/api/actuator/health"
      }
    }
  }

  post {
    success {
      echo "DEV deployment successful 🚀"
    }
    failure {
      echo "DEV deployment failed ❌"
    }
  }
}

